* Objetivo do projeto

Techday foi um concurso realizado pela plataforma educadional [[https://www.dio.me/][dio.me]] em parceria com o Carrefour com o objetivo de recrutar novos  
funcionários. Esse repositório foi elaborado para a minha partipação no concurso. O objetivo foi criar um site usando duas api fornecidas pelos realizadores do 
concurso. ATENÇÃO: dependendo da data que você estiver vizualizando as apis pode ocorrer de terem sido desativadas, dependendo das configurações do seu navegador elas tambem não poderão funcionar. Para resolver isso recomendo o plugin Moesif Origin & CORS Changer ou o equivalente.

A primeira api é responsável por procurar lojas nas proximidades, tendo como argumento um CEP aqui representado por 00000000:

#+begin_src js
https://mercado.carrefour.com.br/api/checkout/pub/regions?country=BRA&postalCode=00000000
#+end_src

A segunda vai retornar os itens disponíveis em uma loja tendo como argumento o id da loja desejada, tal id pode ser obtido utilizando a api anterior. Um 
detalhe para se acaso você  notar alguns bugs a api irá retornar  a uma lista, independente do valor para o id colocado, funcionando mesmo com um valor 
vazio, abaixo a api, foi ultilizado XXXXXXXXXXXX para representar o id:

#+begin_src js
https://mercado.carrefour.com.br/api/catalog_system/pub/products/search?fq=XXXXXXXXXXXX
#+end_src

** Tecnologias utilizadas

Para a criação dessa aplicação utilizei principalmente 2 frameworks e uma biblioteca de ícones chamada react-icons.

*** nextJs

O primeiro foi o nextJs o auto intitulado framework react para produção, ele foi selecionado por possuir todos os recursos do React com o diferencial de 
construir nativamente páginas optimizadas para SEO o que faz com que o site seja melhor rankiado pelos mecanismos de busca como Google, Bing e DuckDuckGo. Aqui temos uma comparação entre os códigos gerados pelos frameworkes {mostra o slide} como você pode ver o código do react possui poucas linhas. 

*** tailwind

Para realizar a estilização do site utilizei o frameworkTailind CSS um framework similar ao Boostrap porém focado em utilidades ao invés de componentes 
tornando-o muito mais flexível.

*** React icons

Uma biblioteca que reúne ícones de diversos estilos

** Estrutura do site

O website é constituído por 3 páginas 

*** Index

A página inicial da aplicação, nela estão localizados os componentes modalStores (responsáveis pela busca de lojas) e SearchProducts componente que 
renderiza os produtos assim como realiza sua busca.

*** Carrinho

Página que pode ser acessada clicando no ícone do carrinho na página index, aqui podemos ver os itens selecionados na página anterior, editarmos sua quantidade, na parte inferior da página temos 2 botões um para salvar a lista e o outro para copiar a lista para a area de transferência.

*** Histórico 

Nessa página podemos ver as listas salvas anteriormente assim como excluí-las ou vê-las no carrinho









